# Generated by Django 4.1.5 on 2023-01-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('text_post', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForum',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('id_post', models.ForeignKey(db_column='id_post', on_delete=django.db.models.deletion.DO_NOTHING, to='data.postforum')),
            ],
        ),
    ]
