# Generated by Django 4.1.5 on 2023-01-26 16:01

import applications.data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesCategories',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image_category_file', models.ImageField(upload_to=applications.data.models.images_path)),
            ],
        ),
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('name_post', models.TextField(max_length=300)),
                ('text_post', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id_category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.DO_NOTHING, to='data.forumcategories')),
            ],
        ),
        migrations.AddField(
            model_name='forumcategories',
            name='image',
            field=models.ForeignKey(db_column='image_source', on_delete=django.db.models.deletion.DO_NOTHING, to='data.imagescategories'),
        ),
        migrations.CreateModel(
            name='CommentForum',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('text_comment', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id_post', models.ForeignKey(db_column='id_post', on_delete=django.db.models.deletion.DO_NOTHING, to='data.postforum')),
            ],
        ),
    ]
