# Generated by Django 4.1.5 on 2023-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentforum',
            name='text_comment',
            field=models.TextField(blank=True),
        ),
    ]
