# Generated by Django 4.1.5 on 2023-01-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_commentforum_text_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforum',
            name='name_post',
            field=models.TextField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
