# Generated by Django 4.1.5 on 2023-01-26 14:22

import applications.data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_postforum_id_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforum',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to=applications.data.models.resources_path),
        ),
    ]
