export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";
export const GET_POST_LIST_FAIL = "GET_POST_LIST_FAIL";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";
