export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";
export const GET_POST_LIST_FAIL = "GET_POST_LIST_FAIL";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_POST_PAGINATION_COUNT_SUCCESS =
  "GET_POST_PAGINATION_COUNT_SUCCESS";
export const GET_POST_PAGINATION_COUNT_FAIL = "GET_POST_PAGINATION_COUNT_FAIL";
export const GET_POST_PAGINATION_NEXT_SUCCESS =
  "GET_POST_PAGINATION_NEXT_SUCCESS";
export const GET_POST_PAGINATION_NEXT_FAIL = "GET_POST_PAGINATION_NEXT_FAIL";
export const GET_POST_PAGINATION_PREVIOUS_SUCCESS =
  "GET_POST_PAGINATION_PREVIOUS_SUCCESS";
export const GET_POST_PAGINATION_PREVIOUS_FAIL =
  "GET_POST_PAGINATION_PREVIOUS_FAIL";
